name: f-BGM
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - augustus==3.5.0
  - biopython[version='1.82,1.82']
  - bokeh==3.3.4
  - git==2.49.0
  - pandas[version='1.3.5,1.3.5']
  - pip==24.2
  - plotly==5.18.0
  - pyhmmer==0.8.1
  - python==3.10.13
  - pytorch-cuda==11.8
  - pytorch==2.2.0
  - torchaudio==2.2.0
  - torchvision==0.17.0
  - pip:
      - fair-esm==2.0.0
      - pygustus==0.8.3
